// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_gAHuuU7SEpRczEax7wENOJs-mKYPjFs',
    appId: '1:643166993436:web:b7bfa711eac8fcd925b3d9',
    messagingSenderId: '643166993436',
    projectId: 'viosatask',
    authDomain: 'viosatask.firebaseapp.com',
    storageBucket: 'viosatask.appspot.com',
    measurementId: 'G-J0YKE6BQM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQENnWEwb8FG0UmUm7e5KBn5h_QM9wzl4',
    appId: '1:643166993436:android:19bc8c065dd92ad425b3d9',
    messagingSenderId: '643166993436',
    projectId: 'viosatask',
    storageBucket: 'viosatask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZoMGqemBX1_KceNEB4TqLZeAmtQ0GWaA',
    appId: '1:643166993436:ios:67e6203dcd43cce225b3d9',
    messagingSenderId: '643166993436',
    projectId: 'viosatask',
    storageBucket: 'viosatask.appspot.com',
    iosBundleId: 'com.example.viosaTask',
  );
}
